### PR TITLE
removed row names from msstats proteins output

### PR DESCRIPTION
**Pull request by jspaezp**
Discussed here:
https://github.com/TalusBio/nf-encyclopedia/issues/29

Also awaiting for internal discussion to make sure it does not break downstream tools

### CODE REVIEW

**Review by cia23 — APPROVED** [review]
Looks good! This change shouldn't affect other tools.

**Comment by jspaezp** [comment]
Thanks for the quick review!! :3

**Comment by wfondrie** [comment]
@jspaezp - can you put in another small PR updating CHANGLOG.md with this change? Thanks!

You can also tack it onto another PR if you want.

**Comment by jspaezp** [comment]
@wfondrie added (this time) the changelog changes to https://github.com/TalusBio/nf-encyclopedia/pull/35/commits/ba25909f66e54b24acde12d21404c35663bbd1ee

**Pull request merged**
